server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/commande_db
    username: postgres
    password: postgres
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: your-hikari-pool
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      properties:
        hibernate:
          use_sql_comments: true
          cache:
            use_second_level_cache: false
            use_query_cache: false
#
#logging:
#  config: classpath:log4j2.xml.old
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#      springframework:
#        web: DEBUG
#        data: DEBUG
#      boot:
#        autoconfigure:
#          data:
#            rest: DEBUG
#            jpa: DEBUG
#            orm: DEBUG
# swagger
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html, /api/docs
    tryItOutEnabled: false
    filter: false
    syntaxHighlight:
      activated: true
