spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionRouteLocator: info
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /actuator
